/*
 * Copyright 2025 arvindand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.arvindand.mcpscaffold.generator;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.processing.Generated;
import javax.lang.model.element.Modifier;

import com.squareup.javapoet.*;

import io.github.arvindand.mcpscaffold.config.ScaffoldConfig;
import io.github.arvindand.mcpscaffold.enhancer.DescriptionEnhancer;
import io.github.arvindand.mcpscaffold.model.ComponentInfo;
import io.github.arvindand.mcpscaffold.model.MethodInfo;
import io.github.arvindand.mcpscaffold.model.ParamInfo;

/**
 * Generates MCP tool-annotated wrapper classes using JavaPoet.
 *
 * <p>For each Spring component (repository or service), generates a corresponding MCP tool class
 * with methods annotated for Spring AI MCP server integration. The annotation classes used are
 * configurable via {@link ScaffoldConfig#annotations()}.
 *
 * @author Arvind Menon
 */
public class McpToolClassGenerator {

  private static final String JAVA_LANG = "java.lang";
  private static final String JAVA_UTIL = "java.util";

  private static final ClassName COMPONENT =
      ClassName.get("org.springframework.stereotype", "Component");

  private final ScaffoldConfig config;
  private final DescriptionEnhancer descriptionEnhancer;
  private final ToolNamingStrategy namingStrategy;
  private final ClassName mcpToolAnnotation;
  private final ClassName mcpToolParamAnnotation;

  public McpToolClassGenerator(ScaffoldConfig config) {
    this.config = config;
    this.descriptionEnhancer = new DescriptionEnhancer(config.descriptions());
    this.namingStrategy = new ToolNamingStrategy();

    // Build annotation ClassNames from config
    var annotationConfig = config.annotations();
    this.mcpToolAnnotation =
        ClassName.get(
            annotationConfig.toolAnnotationPackage(), annotationConfig.toolAnnotationSimpleName());
    this.mcpToolParamAnnotation =
        ClassName.get(
            annotationConfig.paramAnnotationPackage(),
            annotationConfig.paramAnnotationSimpleName());
  }

  /** Generates a JavaFile for the given component. */
  public JavaFile generate(ComponentInfo component) {
    String targetPackage = config.output().targetPackage(component.packageName());
    String targetClassName = config.output().targetClassName(component.className());

    TypeSpec.Builder classBuilder =
        TypeSpec.classBuilder(targetClassName)
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(COMPONENT)
            .addAnnotation(generatedAnnotation());

    // Field for wrapped component
    String fieldName = lowerFirst(component.className());
    ClassName componentType = ClassName.get(component.packageName(), component.className());

    classBuilder.addField(
        FieldSpec.builder(componentType, fieldName, Modifier.PRIVATE, Modifier.FINAL).build());

    // Constructor
    classBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(componentType, fieldName)
            .addStatement("this.$N = $N", fieldName, fieldName)
            .build());

    // Tool methods
    for (MethodInfo method : component.methods()) {
      classBuilder.addMethod(toolMethod(component, method, fieldName));
    }

    return JavaFile.builder(targetPackage, classBuilder.build())
        .addFileComment("Generated by mcp-scaffold. Do not edit manually.")
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }

  private AnnotationSpec generatedAnnotation() {
    return AnnotationSpec.builder(Generated.class)
        .addMember("value", "$S", "io.github.arvindand.mcpscaffold")
        .addMember("date", "$S", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME))
        .addMember("comments", "$S", "MCP Scaffold - Spring AI MCP Tool Generator")
        .build();
  }

  private MethodSpec toolMethod(ComponentInfo component, MethodInfo method, String fieldName) {
    String toolName = namingStrategy.generate(component, method, config.naming());
    String description = descriptionEnhancer.generateToolDescription(component, method);

    // Unwrap Optional return types since we'll use .orElse(null)
    TypeName returnType;
    if (method.returnsOptional()) {
      returnType = parseTypeName(unwrapOptionalType(method.returnType()));
    } else {
      returnType = parseTypeName(method.returnType());
    }

    MethodSpec.Builder builder =
        MethodSpec.methodBuilder(method.name())
            .addModifiers(Modifier.PUBLIC)
            .returns(returnType)
            .addAnnotation(
                AnnotationSpec.builder(mcpToolAnnotation)
                    .addMember(config.annotations().toolNameAttribute(), "$S", toolName)
                    .addMember(config.annotations().toolDescriptionAttribute(), "$S", description)
                    .build());

    // Parameters
    List<String> paramNames = new ArrayList<>();
    for (ParamInfo param : method.parameters()) {
      String paramDesc = descriptionEnhancer.generateParamDescription(param);

      ParameterSpec.Builder paramBuilder =
          ParameterSpec.builder(parseTypeName(param.type()), param.name());

      paramBuilder.addAnnotation(
          AnnotationSpec.builder(mcpToolParamAnnotation)
              .addMember(config.annotations().paramDescriptionAttribute(), "$S", paramDesc)
              .addMember(config.annotations().paramRequiredAttribute(), "$L", !param.nullable())
              .build());

      builder.addParameter(paramBuilder.build());
      paramNames.add(param.name());
    }

    // Body - delegate to wrapped component
    String args = String.join(", ", paramNames);

    if (method.returnsVoid()) {
      builder.addStatement("$N.$N($L)", fieldName, method.name(), args);
    } else if (method.returnsOptional()) {
      builder.addStatement("return $N.$N($L).orElse(null)", fieldName, method.name(), args);
    } else {
      builder.addStatement("return $N.$N($L)", fieldName, method.name(), args);
    }

    return builder.build();
  }

  /**
   * Parses a type string into a TypeName.
   *
   * <p>Handles common types like primitives, List, Optional, Map, etc.
   */
  private TypeName parseTypeName(String typeString) {
    // Handle primitives and boxed primitives
    return switch (typeString) {
      case "void" -> TypeName.VOID;
      case "boolean" -> TypeName.BOOLEAN;
      case "byte" -> TypeName.BYTE;
      case "char" -> TypeName.CHAR;
      case "short" -> TypeName.SHORT;
      case "int" -> TypeName.INT;
      case "long" -> TypeName.LONG;
      case "float" -> TypeName.FLOAT;
      case "double" -> TypeName.DOUBLE;
      // Use unboxed primitives where possible for cleaner output
      // For boxed types used as generics, JavaPoet will use the simple name
      case "String", "java.lang.String" -> ClassName.get(JAVA_LANG, "String");
      case "Boolean", "java.lang.Boolean" -> ClassName.get(JAVA_LANG, "Boolean");
      case "Integer", "java.lang.Integer" -> ClassName.get(JAVA_LANG, "Integer");
      case "Long", "java.lang.Long" -> ClassName.get(JAVA_LANG, "Long");
      case "Double", "java.lang.Double" -> ClassName.get(JAVA_LANG, "Double");
      case "Float", "java.lang.Float" -> ClassName.get(JAVA_LANG, "Float");
      case "Byte", "java.lang.Byte" -> ClassName.get(JAVA_LANG, "Byte");
      case "Short", "java.lang.Short" -> ClassName.get(JAVA_LANG, "Short");
      case "Character", "java.lang.Character" -> ClassName.get(JAVA_LANG, "Character");
      case "Object", "java.lang.Object" -> ClassName.get(JAVA_LANG, "Object");
      default -> {
        // Handle generics like List<User> or Map<PetType, Long>
        if (typeString.contains("<")) {
          int genericStart = typeString.indexOf('<');
          String rawType = typeString.substring(0, genericStart);
          String genericPart = typeString.substring(genericStart + 1, typeString.length() - 1);

          ClassName rawClassName = parseClassName(rawType);

          // Split generic parameters respecting nested generics
          String[] genericParams = splitGenericParams(genericPart);
          TypeName[] typeArgs = new TypeName[genericParams.length];
          for (int i = 0; i < genericParams.length; i++) {
            typeArgs[i] = parseTypeName(genericParams[i].trim());
          }

          yield ParameterizedTypeName.get(rawClassName, typeArgs);
        }

        // Simple class name
        yield parseClassName(typeString);
      }
    };
  }

  /**
   * Splits generic type parameters respecting nested generics.
   *
   * <p>For example, "PetType, Long" returns ["PetType", "Long"], and "Map<String, Integer>,
   * List<String>" returns ["Map<String, Integer>", "List<String>"].
   */
  private String[] splitGenericParams(String genericPart) {
    List<String> params = new ArrayList<>();
    int depth = 0;
    int start = 0;
    for (int i = 0; i < genericPart.length(); i++) {
      char c = genericPart.charAt(i);
      if (c == '<') depth++;
      else if (c == '>') depth--;
      else if (c == ',' && depth == 0) {
        params.add(genericPart.substring(start, i).trim());
        start = i + 1;
      }
    }
    params.add(genericPart.substring(start).trim());
    return params.toArray(String[]::new);
  }

  /**
   * Unwraps Optional type to get the inner type.
   *
   * <p>For example, "Optional<Owner>" returns "Owner", and "java.util.Optional<com.example.Owner>"
   * returns "com.example.Owner".
   */
  private String unwrapOptionalType(String typeString) {
    if (typeString.startsWith("Optional<") && typeString.endsWith(">")) {
      return typeString.substring(9, typeString.length() - 1);
    }
    if (typeString.startsWith("java.util.Optional<") && typeString.endsWith(">")) {
      return typeString.substring(19, typeString.length() - 1);
    }
    return typeString;
  }

  private ClassName parseClassName(String className) {
    // Check if it's a fully qualified name
    if (className.contains(".")) {
      int lastDot = className.lastIndexOf('.');
      String packageName = className.substring(0, lastDot);
      String simpleName = className.substring(lastDot + 1);
      return ClassName.get(packageName, simpleName);
    }

    // Common types without package
    return switch (className) {
      case "List" -> ClassName.get(JAVA_UTIL, "List");
      case "Set" -> ClassName.get(JAVA_UTIL, "Set");
      case "Map" -> ClassName.get(JAVA_UTIL, "Map");
      case "Optional" -> ClassName.get(JAVA_UTIL, "Optional");
      case "Page" -> ClassName.get("org.springframework.data.domain", "Page");
      case "Slice" -> ClassName.get("org.springframework.data.domain", "Slice");
      default -> ClassName.bestGuess(className);
    };
  }

  private String lowerFirst(String s) {
    if (s == null || s.isEmpty()) return s;
    return Character.toLowerCase(s.charAt(0)) + s.substring(1);
  }
}
